# Generated by Django 5.1.5 on 2025-03-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_appointment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='symtom',
            new_name='symptom',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Running', 'Running')], default='Pending', max_length=10),
        ),
    ]
